name: ONDC Rsf Utility Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - "deployment"

jobs:
  deploy-rsf-utility:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH Setup and Cloning Repository
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ./key.pem
          chmod 600 ./key.pem
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ vars.SSH_HOST }} >> ~/.ssh/known_hosts

          ssh -i ./key.pem ${{ vars.SSH_USERNAME }}@${{ vars.SSH_HOST }} -T <<EOF
          REPO_DIR=~/rsf-utility-${{ github.ref_name }}
          echo "Removing existing repository directory if exists"
          rm -rf \$REPO_DIR
          echo "Cloning repository from deployment branch"
          git clone --single-branch --branch deployment https://${{ secrets.GITHUBTOKEN }}@github.com/ONDC-Official/rsf-utility.git \$REPO_DIR
          EOF

      - name: Install Docker Compose (if not installed)
        run: |
          ssh -i ./key.pem ${{ vars.SSH_USERNAME }}@${{ vars.SSH_HOST }} <<EOF
          # Check if Docker Compose is installed
          if ! command -v docker-compose &> /dev/null
          then
            echo "Docker Compose not found. Installing..."
            sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
          else
            echo "Docker Compose is already installed."
          fi
          EOF

      - name: Write secrets to .env on EC2
        run: |
          echo "Writing secrets to .env file"
          ssh -i ./key.pem ${{ vars.SSH_USERNAME }}@${{ vars.SSH_HOST }} <<EOF
          REPO_DIR=~/rsf-utility-${{ github.ref_name }}
          echo "Writing environment variables to .env file"
          echo "PORT=${{ vars.PORT }}" >> \$REPO_DIR/.env
          echo "MONGODB_URI=${{ vars.MONGODB_URI }}" >> \$REPO_DIR/.env

          echo "NODE_ENV=${{ vars.NODE_ENV }}" >> \$REPO_DIR/.env
          echo "SETTLEMENT_AGENCY_URL=${{ vars.SETTLEMENT_AGENCY_URL }}" >> \$REPO_DIR/.env
          echo "SETTLEMENT_AGENCY_ID=${{ vars.SETTLEMENT_AGENCY_ID }}" >> \$REPO_DIR/.env
          echo "SETTLEMENT_AGENCY_KEY=${{ vars.SETTLEMENT_AGENCY_KEY }}" >> \$REPO_DIR/.env
          echo "SUBSCRIBER_ID=${{ vars.SUBSCRIBER_ID }}" >> \$REPO_DIR/.env
          echo "SUBSCRIBER_UNIQUE_ID=${{ vars.SUBSCRIBER_UNIQUE_ID }}" >> \$REPO_DIR/.env
          echo "SUBSCRIBER_PRIVATE_KEY=${{ secrets.SUBSCRIBER_PRIVATE_KEY }}" >> \$REPO_DIR/.env
          echo "LOKI_HOST=${{ vars.LOKI_HOST }}" >> \$REPO_DIR/.env
          echo "CLIENT_ID=${{ secrets.CLIENT_ID }}" >> \$REPO_DIR/.env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> \$REPO_DIR/.env
          echo "LOG_LEVEL=${{ vars.LOG_LEVEL }}" >> \$REPO_DIR/.env
          EOF

      - name: Verify .env and docker-compose.yml files
        run: |
          ssh -i ./key.pem ${{ vars.SSH_USERNAME }}@${{ vars.SSH_HOST }} <<EOF
          REPO_DIR=~/rsf-utility-${{ github.ref_name }}
          # Check if .env and docker-compose.yml files exist
          if [ ! -f \$REPO_DIR/.env ]; then
            echo ".env file not found in \$REPO_DIR!"
            exit 1
          fi
          if [ ! -f \$REPO_DIR/docker-compose.yml ]; then
            echo "docker-compose.yml file not found in \$REPO_DIR!"
            exit 1
          fi
          echo ".env and docker-compose.yml files found."
          EOF

      - name: Automation Mock Server Deployment
        run: |
          echo "Deploying with Docker Compose"
          ssh -i ./key.pem ${{ vars.SSH_USERNAME }}@${{ vars.SSH_HOST }} <<EOF
          REPO_DIR=~/rsf-utility-${{ github.ref_name }}
          cd \$REPO_DIR

          # Ensure the .env and docker-compose.yml files exist
          if [ ! -f .env ]; then
            echo ".env file not found!"
            exit 1
          fi

          if [ ! -f docker-compose.yml ]; then
            echo "docker-compose.yml file not found!"
            exit 1
          fi

          # Start the containers using Docker Compose
          echo "Running docker-compose up -d --build"
          sudo docker compose up -d --build
          EOF
